"""Generate runtime WebP variants; retain the original JPEG source artwork."""
from pathlib import Path
import json
from PIL import Image, ImageOps, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
PUBLIC = ROOT / 'public'
DEST = PUBLIC / 'images'
DEST.mkdir(exist_ok=True)
manifest = {}
for source in sorted(PUBLIC.glob('*.jpeg')):
    image = ImageOps.exif_transpose(Image.open(source)).convert('RGB')
    widths = [96, 192, 384, 640] if source.stem.startswith('avatar') else [160, 320, 640, 960]
    variants = []
    for width in widths:
        width = min(width, image.width)
        if any(v['width'] == width for v in variants):
            continue
        resized = image.resize((width, round(image.height * width / image.width)), Image.Resampling.LANCZOS)
        name = f'{source.stem}-{width}.webp'
        resized.save(DEST / name, 'WEBP', quality=82, method=6)
        variants.append({'src': '/images/' + name, 'width': resized.width, 'height': resized.height})
    manifest['/' + source.name] = variants
(ROOT / 'src/data/imageManifest.ts').write_text('// Generated by scripts/optimize_images.py.\nexport const IMAGE_ASSETS = ' + json.dumps(manifest, indent=2) + ' as const;\n', encoding='utf-8')

# A real portrait and restrained native typography; no invented project metrics.
preview = Image.new('RGB', (1200, 630), '#121212')
draw = ImageDraw.Draw(preview)
draw.rectangle((0, 0, 1200, 8), fill='#1db954')
font_dir = Path('C:/Windows/Fonts')
def font(size, bold=False):
    candidates = [font_dir / ('arialbd.ttf' if bold else 'arial.ttf'), Path('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf')]
    return next((ImageFont.truetype(str(p), size) for p in candidates if p.exists()), ImageFont.load_default(size=size))
portrait = ImageOps.fit(Image.open(PUBLIC / 'avatar.jpeg').convert('RGB'), (270, 270))
mask = Image.new('L', portrait.size)
ImageDraw.Draw(mask).ellipse((0, 0, 269, 269), fill=255)
preview.paste(portrait, (80, 180), mask)
draw.text((405, 148), 'INDEPENDENT DEVELOPER', font=font(20, True), fill='#1db954')
draw.text((405, 195), 'Keybeen', font=font(76, True), fill='#ffffff')
draw.text((410, 305), 'Full-stack app & web developer', font=font(30, True), fill='#ffffff')
draw.text((410, 370), 'Practical projects. Thoughtful interfaces.', font=font(24), fill='#a7a7a7')
draw.text((410, 415), 'Cagayan de Oro, Philippines', font=font(24), fill='#a7a7a7')
draw.text((80, 555), 'keybeen-fullstack-developer.vercel.app', font=font(24), fill='#1db954')
preview.save(PUBLIC / 'social-preview.jpg', quality=88, optimize=True)
print('Original JPEG bytes:', sum(p.stat().st_size for p in PUBLIC.glob('*.jpeg')))
print('WebP variant bytes:', sum(p.stat().st_size for p in DEST.glob('*.webp')))

ImageOps.fit(Image.open(PUBLIC / 'avatar.jpeg').convert('RGB'), (192, 192)).save(PUBLIC / 'apple-touch-icon.png', optimize=True)
