// Generated by scripts/optimize_images.py.
export const IMAGE_ASSETS = {
  "/avatar-spiderman.jpeg": [
    {
      "src": "/images/avatar-spiderman-96.webp",
      "width": 96,
      "height": 129
    },
    {
      "src": "/images/avatar-spiderman-192.webp",
      "width": 192,
      "height": 257
    },
    {
      "src": "/images/avatar-spiderman-384.webp",
      "width": 384,
      "height": 514
    },
    {
      "src": "/images/avatar-spiderman-640.webp",
      "width": 640,
      "height": 857
    }
  ],
  "/avatar.jpeg": [
    {
      "src": "/images/avatar-96.webp",
      "width": 96,
      "height": 96
    },
    {
      "src": "/images/avatar-192.webp",
      "width": 192,
      "height": 192
    },
    {
      "src": "/images/avatar-384.webp",
      "width": 384,
      "height": 384
    },
    {
      "src": "/images/avatar-640.webp",
      "width": 640,
      "height": 640
    }
  ],
  "/coinfession.jpeg": [
    {
      "src": "/images/coinfession-160.webp",
      "width": 160,
      "height": 160
    },
    {
      "src": "/images/coinfession-320.webp",
      "width": 320,
      "height": 320
    },
    {
      "src": "/images/coinfession-640.webp",
      "width": 640,
      "height": 640
    },
    {
      "src": "/images/coinfession-960.webp",
      "width": 960,
      "height": 960
    }
  ],
  "/coming-soon.jpeg": [
    {
      "src": "/images/coming-soon-160.webp",
      "width": 160,
      "height": 160
    },
    {
      "src": "/images/coming-soon-320.webp",
      "width": 320,
      "height": 320
    },
    {
      "src": "/images/coming-soon-640.webp",
      "width": 640,
      "height": 640
    },
    {
      "src": "/images/coming-soon-960.webp",
      "width": 960,
      "height": 960
    }
  ],
  "/findify.jpeg": [
    {
      "src": "/images/findify-160.webp",
      "width": 160,
      "height": 160
    },
    {
      "src": "/images/findify-320.webp",
      "width": 320,
      "height": 320
    },
    {
      "src": "/images/findify-640.webp",
      "width": 640,
      "height": 640
    },
    {
      "src": "/images/findify-960.webp",
      "width": 960,
      "height": 960
    }
  ],
  "/gms.jpeg": [
    {
      "src": "/images/gms-160.webp",
      "width": 160,
      "height": 160
    },
    {
      "src": "/images/gms-320.webp",
      "width": 320,
      "height": 320
    },
    {
      "src": "/images/gms-640.webp",
      "width": 640,
      "height": 640
    },
    {
      "src": "/images/gms-960.webp",
      "width": 960,
      "height": 960
    }
  ],
  "/video-editor.jpeg": [
    {
      "src": "/images/video-editor-160.webp",
      "width": 160,
      "height": 160
    },
    {
      "src": "/images/video-editor-320.webp",
      "width": 320,
      "height": 320
    },
    {
      "src": "/images/video-editor-640.webp",
      "width": 640,
      "height": 640
    },
    {
      "src": "/images/video-editor-960.webp",
      "width": 960,
      "height": 960
    }
  ]
} as const;
